### ISSUE TITLE
Remove 'uom' from table

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage-tiled-gridded-coverage#16]
In today's SWG, we reviewed #3 and decided to take it in a different direction. Since vertical measurements are useless without a vertical datum, we want to encourage GPKG clients to get both the geoid of reference and the units from the SRS. While, it would improve interoperability to have everyone use same SRS, we do not wish to constrain ourselves in this way. (We have always allowed users to use alternate SRSs as long as they are defined in the SRS table.) Therefore we agreed to add EPSG::4979 to the SRS table to encourage people to use it by default.

To make this happen, we agreed to make the following modifications:
- eliminate `uom` from the coverage ancillary table
- mandate the adding of `EPSG::4979` to the SRS table for GeoPackages complying with this extension
- provide guidance regarding the use of the SRS table to find the geoid of reference and the unit of measure

I will produce a pull request for this change. We can review it at next week's SWG.

**Comment by bradh** [comment]
This may hurt GeoTools, which does poorly on 2D<->3D conversions
