### ISSUE TITLE
TBD for naming

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage-tiled-gridded-coverage#20]
This is a tracker for the TBDs that we still have in the `gpkg_extensions` table entries. Needs to be resolved with the OGC naming authority prior to release.

**Comment by jyutzler** [comment]
We determined today that there was no point in putting machine-readable text here. We will be providing human-readable text instead. @fhoubie to update and close ticket when complete.

**Comment by fhoubie** [comment]
Could someone propose definitions for the three tables ?

**Comment by bradh** [comment]
https://github.com/opengeospatial/geopackage-elevation/pull/32 is my opinion. Feel free to use whatever you like, after reading what the spec actually requires (http://www.geopackage.org/spec/#_introduction_2)

**Comment by jyutzler** [comment]
@fhoubie Since we determined that these are not machine-readable, what you have is fine.
Closed in #31

**Comment by jyutzler** [comment]
@fhoubie actually change it to the URL of the spec page like https://github.com/opengeospatial/geopackage-elevation/blob/master/spec/1_tiled_gridded_elevation_data_png.adoc

**Comment by fhoubie** [comment]
@jyutzler, wouldn't it be more stable to use OGC document number and Section in Annex F like
OGC 12-128r12:F11 ? It would point to a specific version of GeoPackage extension.

**Comment by jyutzler** [comment]
Taking discussion to https://github.com/opengeospatial/geopackage/issues/241#issuecomment-248074760

**Comment by jyutzler** [comment]
This ticket is OBE as the document was rewritten to become the Tiled Gridded Coverage Extension.
