### ISSUE TITLE
Difference between data_null and data_missing in gpkg_2d_gridded_coverage_ancillary

### ISSUE THREAD

**Issue by carmenta-geo** [opengeospatial/geopackage-tiled-gridded-coverage#22]
Since I didn't get any replies on the mailing list I'm posting it as a issue here. 

In the table gpkg_2d_gridded_coverage_ancillary there are two columns named data_null and data_missing, these are used to identify areas in the raster with "no data" if we have interpreted the standard correctly. There are however some things that are unclear.

Why is there two separate values? Usually you just have one value indicating "no data" but here we have two separate values, do they represent different things?

Should data_missing and data_null be treated differently when you are reading the raster?

**Comment by jyutzler** [comment]
I think we determined that it is worthwhile to have both of these things, but that we should also have defaults like MAX_INT and MAX_INT - 1. Can someone make the PR?

**Comment by jyutzler** [comment]
The GPKG-EE IE recommended having a single value.
On June 16 the GPKG voted unanimously to make this change.
I'll keep this open until the change is actually made. @ThomasNeirynck

**Comment by jyutzler** [comment]
Fixed in #31
