### ISSUE TITLE
2D CRS considerations - Accuracy of LL-WGS84 - need for epoch

### ISSUE THREAD

**Issue by deanhintz** [opengeospatial/geopackage-tiled-gridded-coverage#26]
At the last EE.IE meeting there was broad agreement that 3D spatial reference should in general be expressed as a 2D spatial reference standard such as epsg, plus a separate vertical spatial reference (such as a separate vertical epsg). This agrees with the general consensus as discussed here under the #19 3D CRS github topic.

This led to some discussion about what it takes to be certain about a given location 2D using LL-WGS84. I expressed some concern that LL-WGS84 can vary significantly based on the time of the obeservation. WGS84 observations are dependent on the epoch or WGS84 realization that they are based on. Every GPS or survey instrument is tuned to a certain WGS84 epoch. This can result in variances of more than 0.7 metres, such as in the case of WGS84 (G730) epoch 1994 vs WGS84 (G1674) epoch 2005. This is due to both differences in the survey station network coordinates used and to tectonic plate movements over time.  Transformations between epochs require a position-dependent velocity model, at least if accuracies of less than 1 meter are required. 

On the other hand, I would agree that not all applications require this level of accuracy, so it may not be warranted to enforce the need to track epoch for all data. I believe it would suffice if we recommended the collection of survey date or epoch as an optional parameter or as a metadata entry. At the end of the day it does come down to the data custodian to maintain good metadata on any datasets they are responsible for, and the accuracy of any given dataset is hard for any standards group to ensure. 

Still, I thought it important to raise this issue that a 2D CRS reference such as LL-WGS84 or epsg:4326 is not enough in and of itself to get sub metre accuracy, and that epoch or survey date would go a long way to raising the usefulness of any given dataset as it would allow for future corrections if and when higher accuracy is needed.

For more info on this see:
see: [https://confluence.qps.nl/pages/viewpage.action?pageId=29855173#WorldGeodeticSystem1984(WGS84)-WGS84realizations]

and:
[http://osgeo-org.1560.x6.nabble.com/Time-dependent-coordinate-transformations-td5179981.html]

**Comment by bradh** [comment]
I don't disagree with the issue, and that for many purposes it would be better to use something other than WGS-84. I don't think we should embed epoch into the CRS, since most users are lucky to understand spatial reference on their GPS, let alone guess with epoch.

I do not think that this is specific to elevation extension, and probably should be raised as a geopackage spec issue, rather than an elevation-extension specific recommendation.

**Comment by jyutzler** [comment]
While the SWG agrees this is an issue, there is broad agreement that it is not solely an elevation extension issue or even a GPKG issue. An action item has been taken to bring this topic up to the OGC OAB and CRS SWG.
