### ISSUE TITLE
gpkg_2d_gridded_coverage_ancillary requirement column names

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage-tiled-gridded-coverage#28]
_Change the requirement column names:_

gpkg_2d_gridded_coverage_ancillary

...

[requirement] Values of the ~~tile_matrix_set_id~~ **tile_matrix_set_name** column SHALL reference values in the gpkg_tile_matrix_set ~~id~~ **table_name** column.

**Comment by bosborn** [comment]
see pull request #29

**Comment by jyutzler** [comment]
Changes accounted for in fc8f693 and 9c214cc
