### ISSUE TITLE
uom should be constrained from UCUM

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage-tiled-gridded-coverage#3]
The UCUM reference for `uom` should be profiled to restrict / constrain the number of values. At least it should be restricted to use of simple lengths (rather than a combination of things that end up being a length, like a velocity measure combined with a time measure).

Ideally there would be a single unit of measure - SI metres - `m`. However realistically we'd need to add at least US feet `[ft_us]` and US "international" feet `[ft_i]` since the target audience is so US-centric.

I think it is generally unreasonable to expect mobile application developers to use anything else (e.g. survey's chains, engineers chains, fathoms, miles, nautical miles) for elevation.

While fixing this, we need to say which name or abbreviation we're supposed to be using from UCUM (e.g. "feet", "[ft_us]", or whatever).

**Comment by jyutzler** [comment]
Just to let you know, we did discuss this today but we decided to delay to get more feedback from around OGC.

**Comment by dr-shorthair** [comment]
Pressure is commonly used as a measure of elevation in the met community.

**Comment by bradh** [comment]
I don't think pressure works for geopackage-elevation. met might use it as reference (e.g. temp at pressure level or U/V on a surface), but it isn't common as an input for the use-cases described in the spec.

**Comment by jyutzler** [comment]
At this point I agree with @bradh. My inclination is to enumerate a small number of acceptable values (taken from UCUM). Otherwise you are essentially forcing developers to implement a UCUM engine. That's not what we want.

**Comment by dr-shorthair** [comment]
BTW - I hope that we are not conflating uom and vertical reference system? The latter requires a datum, direction, and uom.

**Comment by jyutzler** [comment]
@dr-shorthair No, we are not. The UOM is specified here:
https://github.com/opengeospatial/geopackage-elevation/blob/master/spec/1_tiled_gridded_elevation_data.adoc#coverage-ancillary

The coordinate reference system is a core part of GeoPackage as described here:
http://www.geopackage.org/spec/#spatial_ref_sys

Our discussion of how to handle vertical reference systems is here:
https://github.com/opengeospatial/geopackage/issues/116

**Comment by jyutzler** [comment]
"Overcome by events" (See #16)
