### ISSUE TITLE
Multiple Coverage Entries for a single Tile Matrix Set

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage-tiled-gridded-coverage#30]
Currently the schema allows for multiple rows in the `gpkg_2d_gridded_coverage_ancillary` table foreign keying on `tile_matrix_set_name` to the same `gpkg_tile_matrix_set` row.  Does this make sense to have multiple coverages for a single Tile Matrix Set?

If not, should add a unique constraint on the `gpkg_2d_gridded_coverage_ancillary` table `tile_matrix_set_name` column.

**Comment by cclark1984** [comment]
It does not make sense to have multiple coverages for a single Tile Matrix Set. I agree with adding a unique constraint on the gpkg_2d_gridded_coverage_ancillary table tile_matrix_set_name column.
