### ISSUE TITLE
Tile Edges to support 3D Display

### ISSUE THREAD

**Issue by mousebird** [opengeospatial/geopackage-tiled-gridded-coverage#37]
This is more in the nature of a question.

Does the standard support an extra row and column of data values at the edge of each tile?

Essentially this is a one row/column overlap of data values between neighboring tiles.  It's very useful for loading tiles independently and displaying them in 3D.  Without this each individual tile is dependent on its neighbors to generate the right geometry for visual display or interpolation.

**Comment by bosborn** [comment]
I don't believe this would be supported by the current spec without an additional column stating the overlapping pixel size.

My [unreleased implementation](https://github.com/ngageoint/geopackage-java/tree/develop/src/main/java/mil/nga/geopackage/extension/elevation) had to increase the query size and maintain border information while consecutively processing rows.  A bicubic interpolation requires additional overlapping pixels (2 in most cases but 3 on edge cases based upon rounding direction).

**Comment by mousebird** [comment]
I figured, but it's good to know for sure.

Thanks.
