### ISSUE TITLE
mismatch for `tile_matrix_set_id`

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage-tiled-gridded-coverage#8]
The gpkg_2D_gridded_coverage_ancillary table definition has a column `tile_matrix_set_id`, which is supposed to be an integer that is a foreign key to `id` in `gpkg_tile_matrix_set`.

Unfortunately there is no `id` in `gpkg_tile_matrix_set` : http://www.geopackage.org/spec/#tile_matrix_set_data_table_definition

Suggest this be a FK to the `table_name` in `gpkg_tile_matrix_set`. It could also be possible to use the `rowid` if we are confident that no-one creates `gpkg_tile_matrix_set` using the `WITHOUT ROWID` optimisation (https://www.sqlite.org/withoutrowid.html).

**Comment by jyutzler** [comment]
https://github.com/opengeospatial/geopackage-elevation/blob/master/spec/1_tiled_gridded_elevation_data.adoc#gpkg_2D_gridded_coverage_ancillary_table

**Comment by jyutzler** [comment]
http://www.geopackage.org/spec/#tile_matrix_set_data_table_definition

**Comment by jyutzler** [comment]
In today's SWG we agreed to change `id` to `table_name`.
